# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=123, upload_to=''),
            preserve_default=False,
        ),
    ]
