# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/thumbnails'),
        ),
    ]
