# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20171120_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/thumbnails/%Y/%m/%d'),
        ),
    ]
